### ISSUE TITLE
GetDelegationToken blows up due to the same key being added to a dictionary twice

### ISSUE THREAD

**Issue by andersosthus** [auth0/Auth0.Windows8.Cs#5]
The key "target" is added twice to the parameters dictionary at line https://github.com/auth0/Auth0.Windows8.Cs/blob/master/Auth0Client/Auth0Client.cs#L254

**Comment by siacomuzzi** [comment]
Fixed @ [Auth0.Windows8.Cs v1.3.1](https://www.nuget.org/packages/Auth0.Windows8.Cs)

Thanks for reporting!
